train:
  name: Li
  num_epoches: 60
  batch_size: 100

model:
  name: resnet18_imgenet
  num_classes: 10

ind_model:
  name: resnet18_imgenet
  num_classes: 10

dataset:
  name: imagenet
  root: ~/data/small_imagenet/

optimizer:
  name: SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True

sur_optimizer:
  name: SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [20, 35, 50]
  gamma: 0.2


watermark_len : 100
used_wm_len : 100
wm_batch_size : 20
num_ref_model : 10
num_ind_model : 2
num_sur_model: 5 
num_fint_model: 5
logdir : log/imagenet/
modeldir : checkpoint/imagenet/
imgdir : half1_resnet18_eps16
randomseed : 0
eps : 16
alpha : 0.03
un_loss_threshold : 50
ta_loss_threshold : 1.0e-6